"""POLICY -> FIRMWARE export: dump an SB3 policy's deterministic path to C arrays
plus a dependency-free C forward pass, then VERIFY the C implementation bit-for-bit
(within float tolerance) against torch on random inputs before anything ships.

The exported network is the policy's deterministic actor: obs -> [feature extractor
is identity for MlpPolicy] -> mlp_extractor.policy_net (2x64 tanh by default) ->
action_net (linear) -> tanh-squash? SB3 PPO emits UNSQUASHED means; robot_api clips
to [-1,1] — the firmware does the same clip.

Usage: python3 _export_firmware.py ../mujoco/models/dummy13_v3_omni_smooth_C.zip walk
   -> writes policy_walk.h (+ verifies via cc-compiled test harness)
"""
import os, sys, subprocess, tempfile

import numpy as np
import torch

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "mujoco"))
os.chdir(os.path.join(HERE, "..", "mujoco"))

from stable_baselines3 import PPO

model_path = sys.argv[1] if len(sys.argv) > 1 else "models/dummy13_v3_omni_smooth_C.zip"
tag = sys.argv[2] if len(sys.argv) > 2 else "walk"

p = PPO.load(model_path, device="cpu")
net = p.policy
layers = []
seq = net.mlp_extractor.policy_net
for m in seq:
    if isinstance(m, torch.nn.Linear):
        layers.append((m.weight.detach().numpy(), m.bias.detach().numpy(), "tanh"))
w = net.action_net.weight.detach().numpy()
b = net.action_net.bias.detach().numpy()
layers.append((w, b, "linear"))

obs_dim = layers[0][0].shape[1]
act_dim = layers[-1][0].shape[0]
print("export %s: obs %d -> %s -> act %d"
      % (tag, obs_dim, [l[0].shape[0] for l in layers[:-1]], act_dim))

# ---- emit header ----
def carr(name, a):
    flat = a.astype(np.float32).ravel()
    body = ",".join("%.9ef" % v for v in flat)
    return "static const float %s[%d] = {%s};\n" % (name, len(flat), body)

h = ["// AUTO-GENERATED by _export_firmware.py — do not edit.",
     "// Source: %s" % os.path.basename(model_path),
     "// Deterministic actor: obs[%d] -> action[%d]; caller clips to [-1,1]." % (obs_dim, act_dim),
     "#pragma once",
     "#define POLICY_%s_OBS %d" % (tag.upper(), obs_dim),
     "#define POLICY_%s_ACT %d" % (tag.upper(), act_dim),
     "#define POLICY_%s_NLAYERS %d" % (tag.upper(), len(layers))]
sizes = []
for i, (W, B, act) in enumerate(layers):
    h.append(carr("policy_%s_w%d" % (tag, i), W))
    h.append(carr("policy_%s_b%d" % (tag, i), B))
    sizes.append((W.shape[0], W.shape[1], 1 if act == "tanh" else 0))
h.append("static const int policy_%s_shape[][3] = {%s};"
         % (tag, ",".join("{%d,%d,%d}" % s for s in sizes)))
h.append("""
static inline void policy_%(t)s_forward(const float* obs, float* act) {
    static float buf_a[256], buf_b[256];
    const float* src = obs;
    float* dst = buf_a;
    const float* Ws[] = {%(ws)s};
    const float* Bs[] = {%(bs)s};
    for (int L = 0; L < POLICY_%(T)s_NLAYERS; L++) {
        int out = policy_%(t)s_shape[L][0], in = policy_%(t)s_shape[L][1];
        for (int o = 0; o < out; o++) {
            float s = Bs[L][o];
            const float* wrow = Ws[L] + o * in;
            for (int i = 0; i < in; i++) s += wrow[i] * src[i];
            dst[o] = policy_%(t)s_shape[L][2] ? tanhf(s) : s;
        }
        src = dst;
        dst = (dst == buf_a) ? buf_b : buf_a;
    }
    const float* fin = (dst == buf_a) ? buf_b : buf_a;
    for (int o = 0; o < POLICY_%(T)s_ACT; o++) {
        float v = fin[o];
        act[o] = v > 1.f ? 1.f : (v < -1.f ? -1.f : v);
    }
}
""" % {"t": tag, "T": tag.upper(),
       "ws": ",".join("policy_%s_w%d" % (tag, i) for i in range(len(layers))),
       "bs": ",".join("policy_%s_b%d" % (tag, i) for i in range(len(layers)))})
out_h = os.path.join(HERE, "policy_%s.h" % tag)
open(out_h, "w").write("\n".join(h))
print("wrote %s (%.0f KB)" % (out_h, os.path.getsize(out_h) / 1024))

# ---- verify: compile a local test harness, compare against torch ----
test_c = r"""
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "policy_%(t)s.h"
int main(int argc, char** argv) {
    FILE* f = fopen(argv[1], "rb");
    static float obs[POLICY_%(T)s_OBS], act[POLICY_%(T)s_ACT];
    int n = atoi(argv[2]);
    for (int k = 0; k < n; k++) {
        fread(obs, sizeof(float), POLICY_%(T)s_OBS, f);
        policy_%(t)s_forward(obs, act);
        fwrite(act, sizeof(float), POLICY_%(T)s_ACT, stdout);
    }
    return 0;
}
""" % {"t": tag, "T": tag.upper()}
with tempfile.TemporaryDirectory() as td:
    cpath = os.path.join(td, "t.c")
    open(cpath, "w").write(test_c)
    exe = os.path.join(td, "t")
    subprocess.run(["cc", "-O2", "-I", HERE, cpath, "-lm", "-o", exe], check=True)
    rng = np.random.default_rng(0)
    N = 500
    obs = rng.normal(0, 1.5, (N, obs_dim)).astype(np.float32)
    obs_file = os.path.join(td, "obs.bin")
    obs.tofile(obs_file)
    res = subprocess.run([exe, obs_file, str(N)], capture_output=True, check=True)
    c_out = np.frombuffer(res.stdout, np.float32).reshape(N, act_dim)
    with torch.no_grad():
        t_out, _ = p.predict(obs, deterministic=True)
    t_out = np.clip(t_out, -1, 1)
    err = np.abs(c_out - t_out).max()
    print("C-vs-torch max abs err over %d random obs: %.2e %s"
          % (N, err, "VERIFIED" if err < 1e-4 else "*** MISMATCH ***"))
    if err >= 1e-4:
        sys.exit(1)
